import type { Metadata } from "next";
import "./globals.css";
import { Kode_Mono, DM_Sans, Rubik } from "next/font/google";
import Navbar from "./components/Navbar";

const kodeMono = Kode_Mono({
  subsets: ["latin"],
  variable: "--font-kode-mono",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kodeMono.variable} ${dmSans.variable} ${rubik.variable} h-svh bg-gradient-to-b bg-linear-to-bl from-background to-purple/10 bg-fixed`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
